name: 'Install Specialised Amulet Compiler Version'
description: 'Build, publish and install this library specialised for the installed compiler. Requires Python, build and twine.'
inputs:
  twine-username:
    description: 'The twine username'
  twine-password:
    description: 'The twine password'
outputs:
  version:
    description: "The version number of the installed library."
    value: ${{ steps.get-version.outputs.version }}
  suffix:
    description: "The compiler suffix"
    value: ${{ steps.get-version.outputs.suffix }}
runs:
  using: "composite"
  steps:
    - name: Build Amulet-Compiler-Version
      shell: bash
      env:
        AMULET_FREEZE_COMPILER: 1
      run: |
        python -m build --wheel "${{ github.action_path }}"/../../..

    - name: Publish Amulet-Compiler-Version
      shell: bash
      env:
        TWINE_USERNAME: ${{ inputs.twine-username }}
        TWINE_PASSWORD: ${{ inputs.twine-password }}
      run: |
        twine upload "${{ github.action_path }}"/../../../dist/* --skip-existing

    - name: Install Amulet-Compiler-Version
      shell: bash
      run: |
        python -m pip install "${{ github.action_path }}"/../../../dist/amulet_compiler_version-*.whl

    - name: Get __version__
      id: get-version
      shell: bash
      run: |
        version=$(python -c "import amulet_compiler_version; print(amulet_compiler_version.__version__)")
        echo "version=$version" >> "$GITHUB_OUTPUT"
        suffix=$(python -c "import amulet_compiler_version; print(f\".{'.'.join(amulet_compiler_version.__version__.split('.')[3:])}\")")
        echo "suffix=$suffix" >> "$GITHUB_OUTPUT"
